services:
  web:
    build: ./django
    container_name: django_petshop
    volumes:
      - ./django:/app
      - ./django/media:/app/media # adiciona o volume para m√≠dia
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: petshopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: django-insecure-dev-key-change-in-production
      DJANGO_DEBUG: "True"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_petshop
    restart: always
    environment:
      POSTGRES_DB: petshopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
