services:
  web:
    build: ./django
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    environment:
      # O Docker vai pegar o valor direto do ambiente (Codespaces Secrets)
      - POSTGRES_DB=${SUPABASE_DB_NAME}
      - POSTGRES_USER=${SUPABASE_DB_USER}
      - POSTGRES_PASSWORD=${SUPABASE_DB_PASSWORD}
      - POSTGRES_HOST=${SUPABASE_DB_HOST}
      - POSTGRES_PORT=6543
      - DJANGO_DEBUG=True
    # REMOVA OU COMENTE AS LINHAS ABAIXO:
    # env_file:
    #   - .env 
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_petshop
    restart: always
    environment:
      POSTGRES_DB: petshopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
